### ISSUE TITLE
Música y efectos

### ISSUE THREAD

**Issue by vcalzadaga** [CIFP-Jose-luis-Garci/FabricFigures#1]
Búsqueda de músicas y efectos para el juego

- [x] Músicas
- [x] Efectos
- [x] Estilo

**Comment by vcalzadaga** [comment]
En esta página hay bases de datos de efectos de juegos jgkjerkot

**Comment by InmaJimPe** [comment]
En el apartado de la música se han elegido estas obras como una idea aproximada del estilo general deseado:
 
Mussorgsky, Pictures at an exhibition. 
Penderecki, Threnody for the Victims of Hiroshima
Frank Matin, Trois Chants de Noel
Pure Sky, Yu-Peng Chen
Jordy Chandra, Guizhong Lullaby

**Comment by BlancaSJG** [comment]
**Efectos**
Navegar por opciones: al pasar por encima de una opción efecto sutil.
Seleccionar opción: al clickear en una opción efecto sutil mas sonoro.
Caída al punto de inicio: sonido de aire y tierra golpeada.
Caminar: pasos por la tierra.
Saltar: efecto de esfuerzo al saltar y caída ligera al suelo.
Correr: efecto de esfuerzo al correr y sonido de pasos.
Reposo: respiración cansada.
Ataque: efecto de espada.
Daño personaje: efecto de daño.
Obtención de item: efecto de recogida.
Juguetes: sonidos característicos de cada uno.
Proximidad a peligro: efecto de tensión.
Enemigos: efectos de susurros y rugidos.
Daño enemigos: efecto de daño.
Boss final: múltiples voces y susurros.
Daño Boss final: efecto de daño.
Teleférico: efecto de mecanismo en movimiento y parada.
Moneda: efecto de moneda al caer.
Cascanueces: efecto de madera vieja.
Puertas de la ciudad: efecto de puertas chirriando.

**Comment by BlancaSJG** [comment]
Estos son diferentes efectos que he recopilado, habría que mirar cuales se ajustan mejor y seguir buscando otros.

Felt:
https://freesound.org/people/Tdude9000/sounds/138307/
https://freesound.org/people/luisa115/sounds/412652/
https://freesound.org/people/kyles/sounds/452049/
https://freesound.org/people/fiveletterfruit/sounds/517772/
https://freesound.org/people/marchelonia/sounds/588278/
https://freesound.org/people/Merrick079/sounds/568170/
https://freesound.org/people/14G_Panska_Niklova_Michaela/sounds/422141/
https://freesound.org/people/qubodup/sounds/188056/
https://freesound.org/people/felixyadomi/sounds/456374/
https://freesound.org/people/claymorexx/sounds/472116/

Posibles efectos para enemigos:
https://freesound.org/people/Huminaatio/sounds/189278/
https://freesound.org/people/Jace/sounds/19110/
https://freesound.org/people/feehsp/sounds/390942/
https://freesound.org/people/Pipelenisf/sounds/560248/
(niños) https://freesound.org/people/BrainClaim/sounds/267178/
https://freesound.org/people/the_yura/sounds/211526/
https://freesound.org/people/FlechaBr/sounds/340161/

Efectos ambiente:
https://freesound.org/people/HorrorAudio/sounds/431979/
https://freesound.org/people/Beetlemuse/sounds/536353/
https://freesound.org/people/smokinghotdog/sounds/584914/
https://freesound.org/people/14G_Panska_Niklova_Michaela/sounds/422141/
https://freesound.org/people/felix.blume/sounds/410517/
https://freesound.org/people/qubodup/sounds/169945/
https://freesound.org/people/juan9826/sounds/429912/
https://freesound.org/people/pfranzen/sounds/339798/
https://freesound.org/people/xtrgamr/sounds/265544/
https://freesound.org/people/qubodup/sounds/211646/
https://freesound.org/people/qubodup/sounds/211648/
https://freesound.org/people/qubodup/sounds/212431/
https://freesound.org/people/jobro/sounds/201568/

Juguetes:
https://freesound.org/people/sergiosmarinis/sounds/346764/
https://freesound.org/people/Iamgiorgio/sounds/371309/

Otros:
https://freesound.org/people/Bastianhallo/sounds/434050/
https://freesound.org/people/tim.kahn/sounds/507735/
