### ISSUE TITLE
Alcance

### ISSUE THREAD

**Issue by MayaSantayana** [CIFP-Jose-luis-Garci/FabricFigures#11]
Hasta donde se va a desarrollar el videojuego.

**Comment by Javianim17** [comment]
La historia del juego nos llevaría a través del limbo de los juguetes, comenzando por una zona de tutorial en la cual se enseñaría al jugador a utilizar las mecánicas propias del juego, así como los saltos, ataques...etc, tras esta zona de tutorial, habría diferentes luchas y peleas con enemigos los cuales gradualmente irían subiendo de dificultad por lo que cada lucha costará mas que la anterior, no sería solo que por cada lucha los enemigos fueran mas fuertes si no que por cada lucha aparecerían nuevos enemigos mas fuertes acompañado por enemigos anteriores. 
Estas luchas tendrían como punto final un Boss, el cual tendremos que derrotar para conseguir la moneda, la cual necesitamos para activar el mecanismo del teleférico-tiovivo el cual nos llevará hasta la ciudad de los juguetes.

**Comment by Javianim17** [comment]
En cuanto a niveles, desarrollaríamos el tutorial inicial en el que se enseña al jugador las mecánicas principales como movimientos, saltos o ataques, y además el primer nivel el cual comprende desde el final del tutorial hasta después de derrotar al Boss y llegar a la ciudad de los juguetes.
En cuanto a modelado de personajes, estaría el modelado del protagonista(con sus armas) , 4-5 enemigos, y un NPC el cual nos recibirá al llegar ala ciudad de los juguetes, además de los personajes, se modelaría el entorno con assets importados y algunos modelados propios cuando sea necesario.
Implementaríamos un rigg completo al protagonista, y los enemigos también tendrían rigg solo que tal vez mas simple para optimizar y acelerar el desarrollo
Y en cuanto a las mecánicas, se implantarían varios ataques, saltos, movimiento y una adicional, si es posible, de balanceo.
