### ISSUE TITLE
Público objetivo

### ISSUE THREAD

**Issue by MayaSantayana** [CIFP-Jose-luis-Garci/FabricFigures#12]
A que perfil de persona va dirigido nuestro juego.

**Comment by BlancaSJG** [comment]
Nuestro target serían jugadores de entre 16 y 30 años, aproximadamente. Deben tener suficiente desarrollo emocional para entender el trasfondo de la historia, ya que la crudeza que pretende transmitir es de más difícil comprensión para un público demasiado joven.
Aun así, la clasificación PEGI sería 18, ya que contendría escenas o ciertas referencias a una violencia bastante cruda. 
Nuestro público quiere consumir un juego con historia, que les haga pensar y produzca sentimientos encontrados, mientras recorren un mundo rodeado por el suspense y juguetes, ahora tétricos, que les hagan recordar su infancia. 
En resumen, consumidores de 16-30 años, nostálgicos y apasionados por los juegos de terror con historia.

**Comment by vcalzadaga** [comment]
Tema cerrado
