### ISSUE TITLE
Equipo humano

### ISSUE THREAD

**Issue by MayaSantayana** [CIFP-Jose-luis-Garci/FabricFigures#13]
Quienes participamos en el proyecto.

**Comment by InmaJimPe** [comment]
_Equipo humano_

Se comenzó el proyecto entre cinco personas, desafortunadamente dos de ellas abandonaron el equipo. En los últimos meses un nuevo compañero se unió al desarrollo del videojuego.
Javier Navarro, el nuevo modelador recién llegado del CES, un chico entusiasta y trabajador.
Maya Pardo, programadora experimentada en el campo de los videojuegos y entusiasta del diseño de personajes.
Blanca San José, técnico de sonido e imagen con un amplio repertorio de proyectos y pasión por el gore.
Inma Jiménez, animadora 3D y 2D enfocada al entorno de los videojuegos y gran experiencia laboral.

Somos un equipo variado y con mucho amor por el arte audiovisual, con grandes aspiraciones, estilos diferentes y personalidades, aunque diferentes, afines.

**Comment by vcalzadaga** [comment]
Cuando tengáis un tema cerrado, además de pasarlo a Verify, debéis cerrarlo para que os dé progreso (botón inferior). Os lo cierro yo

**Comment by InmaJimPe** [comment]
_Equipo humano_

El equipo de desarrollo de FabricFigures se compone actualmente de cinco miembros. En sus comienzos, se contó con la ayuda de dos compañeros que posteriormente abandonaron el proyecto y finalmente se ha completado el grupo con la incorporación de Javier Navarro.

Integrantes

Javier Navarro: Modelador profesional, recién llegado del CES, un chico entusiasta y trabajador.
Maya Pardo: Programadora, experimentada en el campo de los videojuegos y entusiasta del diseño de personajes.
Blanca San José: Técnico de sonido e imagen con un largo recorrido como especialista dentro del cine gore.
Inma Jiménez: Animadora 3D y 2D con gran experiencia laboral en el ámbito de los videojuegos.

El equipo destaca por su amor hacia el arte audiovisual, la diversidad de estilos y el espíritu de cooperación, aunando sus distintos enfoques en pos del mejor de los resultados.
