### ISSUE TITLE
Introducción del proyecto

### ISSUE THREAD

**Issue by MayaSantayana** [CIFP-Jose-luis-Garci/FabricFigures#14]
- [x]  Sinopsis del videojuego
- [x]  Características principales (mecánicas, narrativa, etc.)
- [x]  Género
- [x]  Plataforma

**Comment by BlancaSJG** [comment]
La plataforma sería en PC, pero se jugaría con mando, ya que es más cómodo.
Según datos de AEVI, los PC son los terceros dispositivos mas utilizados.

**Comment by BlancaSJG** [comment]
Los géneros que definen nuestro juego son Acción,Aventura y Estrategia, así como los subgéneros Survival Horror y Plataformas.
Acción: nuestro personaje luchará contra enemigos y para vencerlos tendrá que valerse de agilidad y destreza.
Aventura: Se da gran importancia a la exploración del escenario, lo que ayudará a la resolución de lo puzles.
Estrategia: para vencer a ciertos enemigos tendrás que valerte de estrategias y ser inteligente a la hora de resolver los puzles. 
El Survival Horror es un subgénero en el que se presenta un personaje vulnerable y solitario, en el que se da énfasis a la resolución de acertijos antes que a la ofensiva. La historia, el diseño y la música son de gran importancia.
En nuestro juego implementamos el plataformeo mediante la mecánica de saltos de obstáculos, balanceos con el hilo de nuestro personaje, etc.

**Comment by MayaSantayana** [comment]
### Concepto del juego
Felt, el protagonista de nuestra historia, es un muñeco de arpillera que ha sido separado de su niño. Tras ello comenzará un viaje a través del limbo de los juguetes, donde luchará para avanzar y poder retornar con su dueño. En su búsqueda se encontrará en la gran ciudad de los juguetes, antaño un faro de esperanza para aquellos que han sido abandonados, ahora ruinas. Por suerte algunos de sus habitantes aún conservan la cordura, y le ayudarán a progresar en su camino.

**Comment by MayaSantayana** [comment]
### Características principales
**Narrativa rica:** Tras su llegada al purgatorio, Felt descubrirá poco a poco el pasado y los secretos que oculta este tétrico mundo. A medida que avance las decisiones, su juicio sobre el resto de habitantes, y hasta su propio objetivo se verán cuestionados.
**Estética llamativa:** El estilo oscuro del mundo junto con el contraste de tamaño del personaje principal serán aprovechados a lo largo del juego para crear un ambiente inmersivo y carismático que no se ve a menudo. Eso sí, que sea una historia triste no significa que carezca de momentos de felicidad y belleza.
**Mecánicas:** Los combates, el movimiento y los puzles están entrelazados a lo largo del gameplay para mantener al jugador interesado en sus distintos aspectos sin llegar a ser repetitivo, pero nunca rompiendo el flujo de este.
