### ISSUE TITLE
Control de animaciones con slider

### ISSUE THREAD

**Issue by BlancaSJG** [CIFP-Jose-luis-Garci/FabricFigures#27]
Avanzar o retroceder en una animación según los valores de un slider

**Comment by alhgo** [comment]
Aunque es algo que tengo pendiente (controlar animaciones por código) creo que para este caso, y salvo que sea una animación de cientos de fotogramas, es mejor tener un array de sprites con todos los fotogramas (si los arrastráis al array se añaden solos) y que al cambiar el slider el solo va cambiando el sprite haciendo que el valor del slider coja el elemento del array correspondiente. 

He hecho un commit con el ejemplo, pero os dejo aquí el código (el script lo tiene que tener el slider).

IMPORTANTE: he tenido que instalar el paquete 2D sprite para crear los elementos. Así que ya estamos todos sincronizando

```
//Array que contendrá los sprites de la animación
    [SerializeField] Sprite[] spritesArray;
    //Sprite de la escena que cambiará y su renderer
    //Los arrastro en Unity
    [SerializeField] GameObject sprite;
    SpriteRenderer spriteRenderer;
    //Slider que hará cambiar los sprites
    Slider slider;
    
    void Start()
    {
        //Mediante código, accedo al componente Slider propio
        slider = GetComponent<Slider>();

        //Accedo al renderer del sprite
        spriteRenderer = sprite.GetComponent<SpriteRenderer>();
        //Pongo el primer elemento del array como sprite
        spriteRenderer.sprite = spritesArray[0];

        //Le doy al Slider un valor máximo con el nº de elementos del array menos uno
        slider.maxValue = spritesArray.Length - 1;
        //Me aseguro de que usa valores enteros
        slider.wholeNumbers = true;


    }

    //Este método lo tiene que llamar el slider cada vez que cambia su valor
    public void CambiarSprites()
    {
        //Obtengo el valor al que ha cambiado el slider
        //Lo tengo que convertir en entero ya que es un float por defecto
        int valor = (int)slider.value;
        //Le asigno al sprite que va a cambiar el sprite correspondiente del array
        spriteRenderer.sprite = spritesArray[valor];
    }
```

**Comment by alhgo** [comment]
En cualquier caso, podemos controlar cualquier animación mediante código. [Aquí](https://docs.unity3d.com/ScriptReference/Animation.html) podéis ver todos los métodos.

IMPORTANTE: la variable Animation devuelve un array con todos los clips de animación, y si queremos tocar uno en concreto tenemos que dirigirnos a él por su nombre.  [Aquí](https://docs.unity3d.com/ScriptReference/AnimationState-time.html) tenéis un ejemplo de cómo ir a un tiempo en concreto y [aquí](https://docs.unity3d.com/ScriptReference/AnimationState-speed.html) cómo cambiar su velocidad (positivo hacia adelante, negativo hacia atrás y 0 para pausar. Un ejemplo que llama a una animación llamada "Walk":

```
public Animation anim;

    void Start()
    {
        // Walk backwards
        anim["Walk"].speed = -1.0f;

        // Walk at double speed
        anim["Walk"].speed = 2.0f;
    }
```

**Comment by BlancaSJG** [comment]
https://www.youtube.com/watch?v=iZ5n_aN6CM8&list=LL&index=9
Encontré este video que se ajusta a lo que buscaba
