### ISSUE TITLE
PEGI y Caratula

### ISSUE THREAD

**Issue by BlancaSJG** [CIFP-Jose-luis-Garci/FabricFigures#28]
- [x] Clasificación PEGI
- [x] Diseño de Portada y Contraportada
- [x] Diseño de Poster del juego

**Comment by InmaJimPe** [comment]
[PEGI.pdf](https://github.com/CIFP-Jose-luis-Garci/FabricFigures/files/7996950/PEGI.pdf)

**Comment by MayaSantayana** [comment]
![Cover_Sketch](https://user-images.githubusercontent.com/72383698/152551238-41c1d2ec-3d14-4034-b26a-3eb3f8914813.png)

**Comment by MayaSantayana** [comment]
Full size cover:
[Cover.zip](https://github.com/CIFP-Jose-luis-Garci/FabricFigures/files/8082663/Cover.zip)

Reduced:
![Cover@0 25x](https://user-images.githubusercontent.com/72383698/154338027-a5802e1f-b8c4-40f1-ab0c-9cdd3ef31966.png)
