### ISSUE TITLE
Historia y narrativa

### ISSUE THREAD

**Issue by MayaSantayana** [CIFP-Jose-luis-Garci/FabricFigures#3]
- [x]  Lema
- [x]  Historia
- [x]  Plot points
- [x]  Narrativa

**Comment by BlancaSJG** [comment]
Según la historia, la narrativa podría ser en espina, ya que tenemos un hilo conductor que debe seguir nuestra historia principal. Aunque sea muy lineal, lo que nos interesa es la continuidad de la historia

**Comment by Javianim17** [comment]
Historia

La historia del juego nos llevaría a través del limbo de los juguetes, comenzando por una zona de tutorial en la cual se enseñaría al jugador a utilizar las mecánicas propias del juego, así como los saltos, ataques...etc, tras esta zona de tutorial, habría diferentes luchas y peleas con enemigos los cuales gradualmente irían subiendo de dificultad por lo que cada lucha costará mas que la anterior, no sería solo que por cada lucha los enemigos fueran mas fuertes si no que por cada lucha aparecerían nuevos enemigos mas fuertes acompañado por enemigos anteriores.
Estas luchas tendrían como punto final un Boss, el cual tendremos que derrotar para conseguir la moneda, la cual necesitamos para activar el mecanismo del teleférico-tiovivo el cual nos llevará hasta la ciudad de los juguetes.

**Comment by InmaJimPe** [comment]
Lema

Cuando un juguete es desechado ,¿Vaga su alma por el limbo?  

Plot points

Esta es la historia de un niño con una familia desestructurada. 
En un pasado vivía con sus dos padres, pero la situación abusiva a la que se enfrentaba la madre por culpa de su padre la llevaron a escapar sin poder llevarse a su hijo con ella. Dejándole con nada más que con los únicos recuerdos buenos que tenía y un muñeco de trapo que era a lo que se aferraba cuando las cosas se torcían con su padre.
Después de la huida de su madre, la situación mejoró y había momentos de calma. Pero todo eso se perdía cuando el padre le veía jugando con aquel muñeco. 
Toda la furia nacía de su odio hacia aquella mujer y su creencia de que estaba fomentando a su hijo para que jugase con muñecas, algo que solo debían hacer las niñas según él.

En este punto comienza Felt, nuestro protagonista, un muñeco de trapo a quien controlemos durante el juego. Su objetivo es reunirse con su dueño en un mundo onírico creado por la mente del niño. A medida que avanza luchará contra los miedos y traumas allí presentes, debiendo recolectar objetos que le permitirán avanzar y descubran la historia a los jugadores.
Por el camino, encontrará enemigos y obstáculos relacionados con los pasados traumas del niño, así como NPCs que le ayudarán por el camino.

Finalmente Felt consigue regresar con su niño pero ya es demasiado, el padre en un arrebato de ira le corta la cabeza a su hijo.
En la escena final se aprecia la bobina de Felt vacía, al niño abrazando a su muñeco y en el cuello pequeñas gotas de sangre que caen por la costura que une su cabeza al cuerpo.
