### ISSUE TITLE
Personajes

### ISSUE THREAD

**Issue by MayaSantayana** [CIFP-Jose-luis-Garci/FabricFigures#4]
- [x]  Jugables
- [x]  NPCs
- [x]  Enemigos
- [x]  Historia del personaje, habilidades, aspecto y características

**Comment by Javianim17** [comment]
En primer lugar, como personaje jugable tendríamos a nuestro protagonista, Felt. Es el muñeco de trapo de un niño y el único recuerdo que este conserva de su madre, la cual ya no se encuentra con él, a causa de la trágica situación familiar.
Su aspecto es amable, de formas redondas, por ojos tiene dos botones y a la espalda cargaría con una bobina de hilo, además lleva como una especie de capucha la cual le da un toque misterioso.
Como características destacables está la bondad, al querer volver reunirse con su niño por el cual siente algo parecido a amor o cariño debido a que solo se tienen el uno al otro, pero además tenemos la fortaleza, la valentía al no tener miedo a pelear y luchar contra juguetes y criaturas extrañas, incluso en un lugar tan tenebroso, con tal de volver a ver a su niño.

**Comment by Javianim17** [comment]
Como NPC tendríamos al Cascanueces, el cual nos recibirá una vez bajemos del teleférico-tiovivo que nos transporta desde la zona del vertedero hasta la ciudad de los juguetes, nos daría la bienvenida y nos introduciría a la ciudad.

**Comment by Javianim17** [comment]
Como enemigos tendríamos 4 o 5 juguetes los cuales se encuentran en malas condiciones con miembros del cuerpo de otros juguetes, por así decirlo serían como "zombies" o "criaturas diabólicas" pero con la apariencia de juguetes.
Tendrían diferentes niveles de dificultad de tal modo que haya algunos mas débiles y otros mas fuertes, así como el daño que recibiríamos de sus ataques.
Además, cabe destacar la existencia del "Boss", el cual sería el enemigo final y por tanto el mas fuerte y difícil de derrotar.
