### ISSUE TITLE
Estilo visual

### ISSUE THREAD

**Issue by MayaSantayana** [CIFP-Jose-luis-Garci/FabricFigures#5]
- [ ]  Concept
- [ ]  Diseño de personaje
- [x]  Escenario
- [ ]  Objetos (props)

**Comment by BlancaSJG** [comment]
Esquema del escenario
![escenario](https://user-images.githubusercontent.com/77485293/141279845-9cd2475d-8385-4dc5-8859-22ed3b4581c5.jpg)
