### ISSUE TITLE
Interfaz

### ISSUE THREAD

**Issue by MayaSantayana** [CIFP-Jose-luis-Garci/FabricFigures#6]
- [x]  Mapa de navegación
- [x]  Menús
- [x]  HUD

**Comment by BlancaSJG** [comment]
**Navegación**
![navegcion](https://user-images.githubusercontent.com/77485293/141529034-a94e473a-23f4-4b59-ac47-d01fe8b18d68.png)

**Comment by BlancaSJG** [comment]
![Settings](https://user-images.githubusercontent.com/77485293/141
![Inicio](https://user-images.githubusercontent.com/77485293/141531578-96d01b03-a25d-4abc-aa09-e4ad3ef5c39b.jpg)
531439-28af8378-2fbf-45ee-bb32-c0f62061e7ec.jpg)
![Audio](https://user-images.githubusercontent.com/77485293/141531447-49d6a388-527d-4c7d-8341-276dd40b42c3.jpg)

**Comment by BlancaSJG** [comment]
![Video](https://user-images.githubusercontent.com/77485293/141532012-1ef74987-6906-4fef-81d2-fed8d4b6bfa4.jpg)
![Controles](https://user-images.githubusercontent.com/77485293/141533316-eb468495-09f8-4d96-96d9-17a57c396e9c.jpg)

**Comment by BlancaSJG** [comment]
![Pause](https://user-images.githubusercontent.com/77485293/141534701-7a65f046-e202-4fca-b1b4-a2470e0924be.jpg)

**Comment by BlancaSJG** [comment]
![Inventario](https://user-images.githubusercontent.com/77485293/141537409-7efac09b-29c0-4550-8893-d424a359677c.jpg)

**Comment by BlancaSJG** [comment]
![Hud](https://user-images.githubusercontent.com/77485293/141537533-73536e1c-fa5c-41b9-85fe-6704d387ce38.png)

**Comment by BlancaSJG** [comment]
https://interfaceingame.com/screenshots/hollow-knight-inventory/
