### ISSUE TITLE
Dinámicas y mecánicas

### ISSUE THREAD

**Issue by MayaSantayana** [CIFP-Jose-luis-Garci/FabricFigures#7]
- [x]  Mirar tema 4 :)

**Comment by InmaJimPe** [comment]
Dinámicas

La dinámica principal que predominaría en el FabricFigures es la reflexión, mediante la historia el jugador profundizará en el tema del abuso infantil a medida que descubre la historia detrás del personaje. La angustia de las vidas pasadas de los juguetes abandonados , el sentimiento de recompensa y avance en el juego con la obtención de power-ups.

Mecánicas

La mecánicas presentes en el videojuego serán puzles, exploración, sigilo, estrategia RPG y plataformeo.
