### ISSUE TITLE
Diseño de niveles

### ISSUE THREAD

**Issue by MayaSantayana** [CIFP-Jose-luis-Garci/FabricFigures#9]
- [x]  Objetivos
- [x]  Flujo de juego
- [x]  Niveles
- [x]  Dificultad
- [x]  Tutorial

**Comment by BlancaSJG** [comment]
**Objetivo del jugador**

El objetivo del juego es hacer que Felt vuelva con su niño.
El objetivo del jugador durante la demo es completar el tutorial y llegar a la ciudad.


**Flujo de juego**

Los niveles se organizan de forma secuencial, donde al completar uno se desbloquea el siguiente.
El jugador inicia un nivel en el mismo lugar donde ha terminado el anterior.

El jugador deberá avanzar enfrentándose a diferentes enemigos, recolectando objetos y completando puzles para poder completar el nivel. 
Los enemigos abatidos durante el primer nivel nos darán experiencia y restos de sus almas. Tras entrar en la ciudad, los enemigos, además, dejarán monedas, objetos y restos de sus almas.
Usando estos items, podremos obtener nuevas armas y subir su nivel.

En algunas partes del escenario se esconderán botones, Power Ups, con diferentes características.

Durante la partida se podrá cambiar de armas y acceder al menú de Inventario para subir el nivel de las mismas.  

La banda sonora ayudará a detectar las situaciones de peligro y a entender la atmosfera que rodea ciertas situaciones con las que nos encontraremos durante la partida.  Por ejemplo, en los momentos mas tranquilos del juego, sentiremos la nostalgia que experimenta Felt gracias a la música.


**Niveles del juego**

Tutorial

La partida comenzaría con la llegada de Felt al limbo, apareciendo en un hoyo, en el vertedero de juguetes, del cual no podrá escapar si no es saltando (de esta forma enseñamos al jugador a saltar). Mientras escala la pared del socavón, encontrará una aguja (su arma).
Una vez ha llegado al exterior, se encontrará con el primer enemigo, un enemigo de bajo nivel con el que aprender a atacar, esquivar y moverse por el espacio. 
A continuación, el jugador tendrá que tomar la primera decisión, ir por un camino o por otro. Dependiendo de su elección, se enfrentará a enemigos con mayor vida o a enemigos con ataques a distancia, acompañados de un enemigo normal.
Avanzando por el pasillo de basura, llegará al final del tutorial, a un Boss con el que poner todo lo aprendido en práctica.
Tras acabar con este primer objetivo, el tutorial, el jugador contará con lo conocimientos básicos para continuar por este mundo.

Primer Nivel

Nada mas acabar el tutorial, el espacio se divide en dos caminos, uno estrecho y uno amplio. 
Por el camino amplio, el jugador se encontrará con una serie de enemigos que no podrá vencer nada mas terminar el tutorial.
Por el otro camino, se encontrará con un precipicio por el que tendrá que ir con cuidado para no caer. Siguiendo este paso, hay una risco en el cual se topará con un enemigo de mayor vida, teniendo el jugador que atacar mientras trata de no caer al vacío. 
Pasado el risco llegará a una zona amplia, donde verá las puertas de una ciudad de juguetes y un teleférico para llegar allí. Para poner en marcha el teleférico, deberá insertar una moneda.
A partir de este punto, el jugador debe buscar dicha moneda, la cual posee el Boss de nivel.

Para llegar al territorio del Boss, podrán tomarse tres caminos diferentes que se unirán en una entrada. En cada camino, se enfrentará a diferentes enemigos. 
En el más largo y a la izquierda, se encontrará con un enemigo normal acompañado por uno de mayor vida y otro de ataque a distancia.
En el del medio, habrá un enemigo de ataque a distancia y dos normales.
En el de la derecha, atacarán tres enemigos normales y uno de mayor vida.
La entrada será un punto de descanso donde hacer inventario y subir las armas de nivel con aquello obtenido durante los combates.

Pasada la entrada, encontraríamos al Boss de nivel.
Una vez vencido al Boss de nivel, obtendríamos la moneda con la que accionar el mecanismo del teleférico. 
El teleférico nos llevará por el barranco hasta las puertas de la ciudad, donde un soldadito de plomo nos abrirá las puertas a la ciudad y al siguiente nivel.


**Dificultad**
La dificultad viene dada por la cantidad de enemigos que atacan y las características que presentan. La dificultad y habilidades de los enemigos irán aumentando según avance el nivel y se progrese a lo largo del juego. Debido a esto, el jugador deberá ir obteniendo habilidades y mejoras para poder continuar.
![Captura de pantalla 2021-11-11 135833](https://user-images.githubusercontent.com/77485293/141302124-46c783e4-d188-4688-ba20-d8df5be88108.png)
